<Project Sdk="Microsoft.NET.Sdk.Razor">

    <PropertyGroup>
        <TargetFrameworks>net8.0-android;net8.0-ios;</TargetFrameworks>
        <UseMaui>true</UseMaui>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Update="Microsoft.Maui.Controls" Version="8.0.92" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Update="Microsoft.Maui.Controls.Compatibility" Version="8.0.92" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Update="Microsoft.AspNetCore.Components.WebView.Maui" Version="8.0.92" />
    </ItemGroup>


</Project>
