<Project Sdk="Microsoft.NET.Sdk.Razor">

	<PropertyGroup>
		<!-- Uncomment to also build the tizen app. You will need to install tizen by following this: https://github.com/Samsung/Tizen.NET -->
		<!-- <TargetFrameworks>$(TargetFrameworks);net8.0-tizen</TargetFrameworks> -->

		<!-- Note for MacCatalyst:
            The default runtime is maccatalyst-x64, except in Release config, in which case the default is maccatalyst-x64;maccatalyst-arm64.
            When specifying both architectures, use the plural <RuntimeIdentifiers> instead of the singular <RuntimeIdentifier>.
            The Mac App Store will NOT accept apps with ONLY maccatalyst-arm64 indicated;
            either BOTH runtimes must be indicated or ONLY macatalyst-x64. -->
		<!-- For example: <RuntimeIdentifiers>maccatalyst-x64;maccatalyst-arm64</RuntimeIdentifiers> -->
		<TargetFrameworks Condition="$([MSBuild]::IsOSPlatform('windows'))">$(TargetFrameworks);net9.0-windows10.0.19041.0</TargetFrameworks>
		<OutputType>WinExe</OutputType>

		<!--<RuntimeIdentifier>win-arm64</RuntimeIdentifier>-->

		<RootNamespace>AxCrypt.App.Windows</RootNamespace>
		<UseMaui>true</UseMaui>
		<SingleProject>true</SingleProject>
		<ImplicitUsings>enable</ImplicitUsings>
		<EnableDefaultCssItems>false</EnableDefaultCssItems>
		<Nullable>enable</Nullable>

		<!-- Display name -->
		<ApplicationTitle>AxCrypt</ApplicationTitle>

		<!-- App Identifier -->
		<ApplicationId>axcrypt.net.app.windows</ApplicationId>

		<!--<WindowsPackageType>None</WindowsPackageType>-->

		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">10.0.19041.0</SupportedOSPlatformVersion>
		<TargetPlatformMinVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">10.0.19041.0</TargetPlatformMinVersion>
		<AppxAutoIncrementPackageRevision>True</AppxAutoIncrementPackageRevision>
		<AppxSymbolPackageEnabled>False</AppxSymbolPackageEnabled>
		<!--<HoursBetweenUpdateChecks>24</HoursBetweenUpdateChecks>-->
		<AppxPackageDir>$(BaseOutputPath)bin\ReleaseAppPackages\</AppxPackageDir>

		<AssemblyName>AxCrypt</AssemblyName>
		<Copyright>Copyright © 2012-2026 AxCrypt AB</Copyright>
	</PropertyGroup>
	<PropertyGroup Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows' and '$(Configuration)' == 'Debug'">
		<ApplicationDisplayVersion>3.0.0.0</ApplicationDisplayVersion>
		<ApplicationVersion>3.0.0.0</ApplicationVersion>
		<GenerateAppInstallerFile>False</GenerateAppInstallerFile>
		<GenerateTestArtifacts>True</GenerateTestArtifacts>
		<AxBuildType>Debug</AxBuildType>
	</PropertyGroup>
	<PropertyGroup Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows' and '$(Configuration)' == 'Release'">
		<!-- Versions -->
		<_AxCryptMajor>3</_AxCryptMajor>
		<AxMinorVersion Condition=" '$(AxMinorVersion)' == '' ">0</AxMinorVersion>
		<AxBuildNumber Condition=" '$(AxBuildNumber)' == '' ">1</AxBuildNumber>
		<FinalAppVersion>$(_AxCryptMajor).$(AxMinorVersion).0.$(AxBuildNumber)</FinalAppVersion>
		<ApplicationDisplayVersion>$(FinalAppVersion)</ApplicationDisplayVersion>
		<ApplicationVersion>$(FinalAppVersion)</ApplicationVersion>
		<GenerateAppInstallerFile>True</GenerateAppInstallerFile>
		<GenerateTestArtifacts>False</GenerateTestArtifacts>
		<PublishSelfContained>true</PublishSelfContained>
		<AxBuildType Condition=" '$(AxBuildType)' != '' ">$(AxBuildType)</AxBuildType>
	</PropertyGroup>
	<PropertyGroup Condition="'$(AxBuildType)' == 'Debug'">
		<DefineConstants>$(DefineConstants);AX_DEBUG_BUILD</DefineConstants>
	</PropertyGroup>
	<PropertyGroup Condition="'$(AxBuildType)' == 'Beta'">
		<DefineConstants>$(DefineConstants);AX_BETA_BUILD</DefineConstants>
	</PropertyGroup>
	<PropertyGroup Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows' and '$(RuntimeIdentifierOverride)' != ''">
		<RuntimeIdentifier>$(RuntimeIdentifierOverride)</RuntimeIdentifier>
	</PropertyGroup>

	<ItemGroup>
		<!-- App Icon -->
		<MauiIcon Include="Resources\AppIcon\appicon.svg" />

		<!-- Splash Screen -->
		<MauiSplashScreen Include="Resources\Splash\splash.svg" Color="#512BD4" BaseSize="128,128" />

		<!-- Images -->
		<MauiImage Include="Resources\Images\*" />
		<MauiImage Update="Resources\AppIcon\appicon.svg" BaseSize="168,208" />

		<!-- Custom Fonts -->
		<MauiFont Include="Resources\Fonts\*" />

		<!-- Raw Assets (also remove the "Resources\Raw" prefix) -->
		<MauiAsset Include="Resources\Raw\**" LogicalName="%(RecursiveDir)%(Filename)%(Extension)" />
	</ItemGroup>

	<ItemGroup>
		<Compile Remove="Components\Pages\Home\**" />
		<Content Remove="Components\Pages\Home\**" />
		<EmbeddedResource Remove="Components\Pages\Home\**" />
		<MauiXaml Remove="Components\Pages\Home\**" />
		<None Remove="Components\Pages\Home\**" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\shared\AxCrypt.Abstractions\AxCrypt.Abstractions.csproj" />
		<ProjectReference Include="..\..\shared\AxCrypt.Api\AxCrypt.Api.csproj" />
		<ProjectReference Include="..\..\shared\AxCrypt.Common\AxCrypt.Common.csproj" />
		<ProjectReference Include="..\..\shared\Axcrypt.Content\AxCrypt.Content.csproj" />
		<ProjectReference Include="..\..\shared\AxCrypt.Core\AxCrypt.Core.csproj" />
		<ProjectReference Include="..\..\shared\AxCrypt.Cryptor\AxCrypt.Cryptor.csproj" />
		<ProjectReference Include="..\..\shared\AxCrypt.Mono\AxCrypt.Mono.csproj" />
		<ProjectReference Include="..\AxCrypt.App.Shared.Desktop\AxCrypt.App.Shared.Desktop.csproj" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.Maui.Controls" Version="9.0.90" />
		<PackageReference Include="Microsoft.Maui.Controls.Compatibility" Version="9.0.90" />
		<PackageReference Include="Microsoft.AspNetCore.Components.WebView.Maui" Version="9.0.90" />
		<PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="9.0.7" />
		<PackageReference Include="Microsoft.Toolkit.Uwp.Notifications" Version="7.1.3" />
		<PackageReference Include="PInvoke.User32" Version="0.7.124" />
	</ItemGroup>

	<ItemGroup>
		<Compile Update="Properties\Resources.Designer.cs">
			<DesignTime>True</DesignTime>
			<AutoGen>True</AutoGen>
			<DependentUpon>Resources.resx</DependentUpon>
		</Compile>
	</ItemGroup>

	<ItemGroup>
		<Content Update="Components\Pages\Shared\AlertComponent.razor" />
		<Content Update="Components\Pages\Notification.razor" />
	</ItemGroup>

	<ItemGroup>
		<EmbeddedResource Update="Properties\Resources.resx">
			<Generator>ResXFileCodeGenerator</Generator>
			<LastGenOutput>Resources.Designer.cs</LastGenOutput>
		</EmbeddedResource>
	</ItemGroup>

	<ItemGroup>
		<MauiImage Include="Platforms\Windows\axcryptappicon.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Include="Resources\axcrypticon.ico" />
		<MauiImage Include="Resources\axcrypticon128.png" />
		<MauiImage Include="Resources\documents_white_40px.png" />
		<MauiImage Include="Resources\dropbox_40px.png" />
		<MauiImage Include="Resources\googledrive_40px.png" />
		<MauiImage Include="Resources\skydrive_40px.png" />
	</ItemGroup>

	<ItemGroup>
		<Folder Include="Resources\Images\" />
	</ItemGroup>

	<ItemGroup>
		<None Update="Resources\AppIcon\appicon.ico">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="Resources\logos\axcrypt-icon-150x150.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Update="Resources\logos\axcrypt-icon-310x150.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Update="Resources\logos\axcrypt-icon-310x310.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Update="Resources\logos\axcrypt-icon-44x44.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Update="Resources\logos\axcrypt-icon-71x71.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
	</ItemGroup>

	<ItemGroup>
		<PRIResource Remove="Components\Pages\Home\**" />
	</ItemGroup>

	<PropertyGroup>
		<AppxManifestFile>$(MSBuildThisFileDirectory)Platforms\Windows\Package.appxmanifest</AppxManifestFile>
	</PropertyGroup>
	<Import Project="..\SolutionItems\AxCrypt.Net.App.Build.targets" />
</Project>
