<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Security.Cryptography.ProtectedData" Version="9.0.9" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AxCrypt.Abstractions\AxCrypt.Abstractions.csproj" />
    <ProjectReference Include="..\AxCrypt.Common\AxCrypt.Common.csproj" />
    <ProjectReference Include="..\AxCrypt.Core\AxCrypt.Core.csproj" />
  </ItemGroup>

</Project>
