namespace AxCrypt.Core.Runtime
{
    public enum LicenseCapability
    {
        SecureWipe,
        StrongerEncryption,
        KeySharing,
        RandomRename,
        SecureFolders,
        CloudStorageAwareness,
        PasswordManagement,
        PasswordGeneration,
        DirectSupport,
        StandardEncryption,
        AccountKeyBackup,
        CommunitySupport,
        Premium,
        IncludeSubfolders,
        EncryptNewFiles,
        EditExistingFiles,
        InactivitySignOut,
        Viewer,
        Business,
        PasswordManager,
        ShareSecretFree,
        ShareSecretPasswordManager,
        ShareSecretPremium,
        ShareSecretBusiness,
    }
}