<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AxCrypt.Abstractions\AxCrypt.Abstractions.csproj" />
    <ProjectReference Include="..\AxCrypt.Api\AxCrypt.Api.csproj" />
    <ProjectReference Include="..\AxCrypt.Common\AxCrypt.Common.csproj" />
    <ProjectReference Include="..\Axcrypt.Content\AxCrypt.Content.csproj" />
    <ProjectReference Include="..\BouncyCastle.AxCrypt\src\BouncyCastle.AxCrypt.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <None Remove="Notification\" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Notification\" />
  </ItemGroup>
</Project>
