<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GeneratePackageOnBuild>False</GeneratePackageOnBuild>
  </PropertyGroup>

  <ItemGroup>
    <Compile Update="Resource.zh.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resource.zh.resx</DependentUpon>
    </Compile>
    <Compile Update="Resource.sv.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resource.sv.resx</DependentUpon>
    </Compile>
    <Compile Update="Resource.pt.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resource.pt.resx</DependentUpon>
    </Compile>
    <Compile Update="Resource.nl.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resource.nl.resx</DependentUpon>
    </Compile>
    <Compile Update="Resource.it.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resource.it.resx</DependentUpon>
    </Compile>
    <Compile Update="Resource.es.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resource.es.resx</DependentUpon>
    </Compile>
    <Compile Update="Resource.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resource.resx</DependentUpon>
    </Compile>
    <Compile Update="Resource.de.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resource.de.resx</DependentUpon>
    </Compile>
    <Compile Update="Resource.de.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resource.de.resx</DependentUpon>
    </Compile>
    <Compile Update="Resource.es.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resource.es.resx</DependentUpon>
    </Compile>
    <Compile Update="Resource.fr.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resource.fr.resx</DependentUpon>
    </Compile>
    <Compile Update="Resource.it.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resource.it.resx</DependentUpon>
    </Compile>
    <Compile Update="Resource.ko.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resource.ko.resx</DependentUpon>
    </Compile>
    <Compile Update="Resource.nl.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resource.nl.resx</DependentUpon>
    </Compile>
    <Compile Update="Resource.pl.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resource.pl.resx</DependentUpon>
    </Compile>
    <Compile Update="Resource.pt.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resource.pt.resx</DependentUpon>
    </Compile>
    <Compile Update="Resource.ru.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resource.ru.resx</DependentUpon>
    </Compile>
    <Compile Update="Resource.sv.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resource.sv.resx</DependentUpon>
    </Compile>
    <Compile Update="Resource.tr.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resource.tr.resx</DependentUpon>
    </Compile>
    <Compile Update="Resource.zh.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resource.zh.resx</DependentUpon>
    </Compile>
    <Compile Update="Resource.ar.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resource.ar.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Resource.zh.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resource.zh.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resource.sv.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resource.sv.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resource.pt.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resource.pt.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resource.nl.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resource.nl.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resource.it.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resource.it.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resource.es.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resource.es.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resource.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resource.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resource.de.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resource.de.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resource.de.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resource.de.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resource.es.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resource.es.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resource.fr.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resource.fr.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resource.it.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resource.it.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resource.ko.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resource.ko.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resource.nl.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resource.nl.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resource.pl.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resource.pl.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resource.pt.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resource.pt.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resource.ru.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resource.ru.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resource.sv.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resource.sv.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resource.tr.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resource.tr.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resource.zh.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resource.zh.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resource.ar.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resource.ar.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

</Project>
